### ISSUE TITLE
Integrate with CITI training API to validate training reports

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet-build#1703]
We should investigate whether the CITI API can help us to streamline the training review process. See: 
https://webservices.citiprogram.org/

There is some limited documentation on the beta service at: https://webservices.citiprogram.org/DOC/CITISOAP_Documentation.aspx

> This site ... [will offer] ... member institutions web access to their information over HTTPS and SOAP. Currently in test is the SOAP service against some basic reports from the course completion data tables. RESTful service is still in development.

**Comment by lamawmouk** [comment]
Sounds interesting! They provide a flat file of the users for the course we could potentially utilize.

**Comment by tompollard** [comment]
@lamawmouk Did you have any more thoughts on whether the flat file could help us (or any other services they offer)? 

Perhaps we could reach out to the contact listed at https://webservices.citiprogram.org/DOC/CITISOAP_Documentation.aspx to see if they can provide us with guidance?

**Comment by lamawmouk** [comment]
Thanks @tompollard, I will reach out to them to check about their resource and we could navigate that avenue.

**Comment by lamawmouk** [comment]
This is resolved-pending meeting with CITI staff (ccruciger@citiprogram,org)

**Comment by tompollard** [comment]
@lamawmouk We'll want to document our findings from the initial meeting here. I think the issue is not really resolved until we integrate with the API (or decide that the API isn't what we need).

**Comment by lamawmouk** [comment]
Initial meeting:
- Get approval to be able to create a web service API key/permission to enable client from CITI.
- Create and integrate a client SOAP service. 
This will allow us to make a call to the API which gives the CITI report associated with an email. The API call will provide information such as email address on CITI, scores, completion of report etc. in an XML format. This information can be used to check if the training meets the requirements. 
- Approve all reports automictically or each user individually. 
- A user's email address on PhysioNet must link and match with the CITI email address.
- Curate a python package and integrate it in django.

**Comment by tompollard** [comment]
Thanks for the summary @lamawmouk. Keeping fingers crossed that we get access to the API now! If not, maybe we need to look into what it takes to create our own training account.
